version: 2
registries:
  interlok:
    type: maven-repository
    url: https://nexus.adaptris.net/nexus/content/groups/interlok

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 20
    registries:
      - "interlok"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "all"
    reviewers:
      - sebastien-belin-adp
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    reviewers:
      - sebastien-belin-adp
