name: Approve And Merge Dependabot PR

on:
  pull_request:

jobs:
  approvemerge:
    name: Approve And Merge Dependabot PR
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    # Perform the auto approve action only when the PR is raised by dependabot
    steps:
      - name: Dependabot Metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.6.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        # The following properties are now available:
        #  - steps.dependabot-metadata.outputs.dependency-names
        #  - steps.dependabot-metadata.outputs.dependency-type
        #  - steps.dependabot-metadata.outputs.update-type
      - name: Check If Should Approve And Merge
        id: check-approve-merge
        continue-on-error: true
        if: steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major'
        uses: actions/github-script@v6
        with:
          script: |
            const validDependencies = ["mockito-core","jackson-bom","io.freefair.lombok","com.github.spotbugs","org.owasp.dependencycheck","grpc-protobuf","protobuf-java","grpc-google-cloud-pubsub-v1","google-cloud-pubsub","aws-java-sdk-core","twilio","jnats","activemq-broker"]
            const prDependencies = "${{ steps.dependabot-metadata.outputs.dependency-names }}"
            function hasAtLeastOneDependency() {
              for (const dependency of validDependencies) {
                if (prDependencies.includes(dependency)) {
                  return true;
                }
              }
              return false;
            }
            return hasAtLeastOneDependency()
          result-encoding: string
      - name: Approve a Dependabot PR If Not Already Approved
        continue-on-error: true
        # Only mockito and patch version
        if: steps.check-approve-merge.outputs.result == 'true'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.DEPENDABOT_APPROVE_MERGE_GITHUB_TOKEN}}
      - name: Merge a Dependabot PR
        continue-on-error: true
        # Only mockito and patch version
        if: steps.check-approve-merge.outputs.result == 'true'
        # Auto merge the PR using dependabot command '@dependabot merge'
        run: gh pr comment --body "@dependabot merge" "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.DEPENDABOT_APPROVE_MERGE_GITHUB_TOKEN}}
