name: Approve And Merge Dependabot PR

on:
  pull_request_target:

jobs:
  approvemerge:
    name: Approve And Merge Dependabot PR
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    # Perform the auto approve action only when the PR is raised by dependabot
    steps:
      - name: Dependabot Metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
        # The following properties are now available:
        #  - steps.metadata.outputs.dependency-names
        #  - steps.metadata.outputs.dependency-type
        #  - steps.metadata.outputs.update-type
      - name: Check If Should Approve And Merge
        id: checkapprovemerge
        if: |
          (
            contains(steps.metadata.outputs.dependency-names, 'mockito-core') ||
            contains(steps.metadata.outputs.dependency-names, 'io.freefair.lombok')
          ) && steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: |
          echo "::set-output name=result::true"
      - name: Approve a Dependabot PR If Not Already Approved
        # Only mockito and patch version
        if: steps.checkapprovemerge.outputs.result == 'true'
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Merge a Dependabot PR
        # Only mockito and patch version
        if: steps.checkapprovemerge.outputs.result == 'true'
        # Auto merge the PR using dependabot command '@dependabot merge'
        run: gh pr comment --body "@dependabot merge" "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
